CachingMVC/Models/ContextoBBDD.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CachingMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextoBBDD : DbContext
    {
        public ContextoBBDD()
            : base("name=ContextoBBDD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GATOS> GATOS { get; set; }
    }
}

CachingMVC/Models/ContextoBBDD.Designer.cs
// T4 code generation is enabled for model 'C:\Users\userjull\source\repos\CachingMVC\CachingMVC\Models\ContextoBBDD.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

CachingMVC/Models/ContextoBBDD.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

CachingMVC/Models/GATOS.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CachingMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GATOS
    {
        public string Id { get; set; }
        public string RAZA { get; set; }
        public string ORIGEN { get; set; }
        public string TIPO_PELO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string FECHA_LLEGADA { get; set; }
        public string FOTO { get; set; }
        public string INFO { get; set; }
    }
}

CachingMVC/Models/ModeloCaching.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CachingMVC.Models
{
    public class ModeloCaching
    {
        ContextoBBDD contexto;
        public ModeloCaching()
        {
            contexto = new ContextoBBDD();
        }

        public List<GATOS> GetGatos()
        {
            var consulta = from datos in contexto.GATOS
                           select datos;
            return consulta.ToList();
        }
        
    }
}

CachingMVC/Controllers/CachingController.cs
using CachingMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace CachingMVC.Controllers
{
    public class CachingController : Controller
    {
        ModeloCaching modelo;
        public CachingController()
        {
            modelo = new ModeloCaching();
        }
        //GET:CACHING
        [OutputCache (CacheProfile ="corto")]
        public ActionResult Index(String id)
        {
            ViewBag.Hora = "Hora del sistema: " + DateTime.Now.ToLongTimeString();
            List<GATOS> lista = modelo.GetGatos();
            return View(lista);
        }


        [OutputCache(Duration = 50, VaryByParam = "id",Location = OutputCacheLocation.Client, NoStore =true)]
        public ActionResult Details(String id)
        {

            ViewBag.Hora = "Hora del sistema: " + DateTime.Now.ToLongTimeString();
            GATOS gato = modelo.DetalleGato(id);
            return View(gato);
        }

    }
}

CachingMVC/Views/Caching/Index.cshtml
@model IEnumerable<CachingMVC.Models.GATOS>

@{
    ViewBag.Title = "Index";
}

<h2>GATOS</h2>
<div id="gato"></div>
<h3 style="color:brown">@ViewBag.Hora</h3>
<table class="table">
    <tr>
        <th>IMAGEN</th>
        <th>RAZA</th>
        <th>ORIGEN</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img src="~/Img/@item.FOTO" style="width:100px;height:100px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RAZA)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ORIGEN)
            </td>
            <td>
                @Html.ActionLink("Details", "Index", new { id = item.Id })

            </td>
        </tr>
    }
</table>

CachingMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CACHING MVC", "Index", "Caching", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Vista", "Index", "Caching")</li>  
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>